### ISSUE TITLE
Working branch ?

### ISSUE THREAD

**Issue by george2giga** [CodeConnect/SourceBrowser#116]
Hi ! 
Really like the project, did try the demo and it is great ! 
I'm trying to fork the master branch but I'm getting a bunch of error (VBWalkerUtils doesn't compile for instance, syntax for get & set throws errors).
Can you please point me to a working branch ?
Many thanks !

**Comment by AmadeusW** [comment]
@george2giga we've stopped developing this project when the engine behind _.NET reference source_ was open sourced: https://github.com/KirillOsenkov/SourceBrowser

**Comment by george2giga** [comment]
@AmadeusW that's ok I've managed to get it working, you've done a fantastic job btw, thanks !

**Comment by AmadeusW** [comment]
alright, thanks!
