### ISSUE TITLE
Attributes are not colored correctly 

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#37]
Attributes should be colored as types.
See below:

![image](https://cloud.githubusercontent.com/assets/1249087/5272888/3148040a-7a4f-11e4-91ee-f5b0c0a1ad92.png)

**Comment by JoshVarty** [comment]
As we're just mirroring GitHub for the most part, I'm alright with them being uncolored.

**Comment by AmadeusW** [comment]
I would rather see them coloured, but the colour scheme should be consistent:
If we use Visual Studio colouring, what do we use for Java? InteliJ, Eclipse or GitHub? Perhaps it's the best to stick with GitHub.
