### ISSUE TITLE
Debugging SourceBrowser.Site Intermittently breaks in VS 2015

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#49]
Both myself and @AmadeusW have had issues debugging SourceBrowser in Visual Studio 2015. Occasionally, we won't be able to inspect variables and adding a watch displays the error message:

>error CS1703: Multiple assemblies with equivalent identity have been imported: 'Microsoft.Build.Framework.dll' and 'Microsoft.Build.Framework.dll'. Remove one of the duplicate references.

Within Roslyn this message appear to be found here: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/ReferenceManager/CommonReferenceManager.Resolution.cs,628

I'm creating this issue to see if any other contributors notice this problem. If so, please report it here and we'll try to repro for the Roslyn team.

**Comment by JoshVarty** [comment]
Have you seen this recently @AmadeusW? It seemed to stop for me...

**Comment by AmadeusW** [comment]
I've followed steps from Microsoft's support email:

> It seems that you are hitting an issue that. Let’s see if reverting to the old EE helps clear your issue:  Debug/Options/General -> Use the legacy C# and VB expression evaluators (you can find details on the above blog post as well).

Did you follow the same steps? I think I've forwarded you that email.

**Comment by JoshVarty** [comment]
I didn't even do that, but I still haven't encountered this bug in weeks. I'm going to close it and we'll reopen it if we see it again.

**Comment by AmadeusW** [comment]
Sounds good, let's keep the issue list clean
