### ISSUE TITLE
Unify CSWalker and VBWalker

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#65]
There is very little difference between these two classes, but every time we need to update one, we have to mirror the changes in the other. We should make these one single class that works for both C# and VB .Net.

**Comment by AmadeusW** [comment]
Since the base class is either VisualBasicSyntaxWalker or CSharpSyntaxWalker, and there can be only one base class, we can accomplish this by moving function logic to another class. What are your thoughts?

**Comment by JoshVarty** [comment]
We could probably inherit from [SyntaxWalker](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Syntax/SyntaxWalker.cs,201af9b1a46bc9d4) instead, but I haven't played around with this yet.

**Comment by AmadeusW** [comment]
I attempted working on this but I encountered errors about ambiguous references:

> The call is ambiguous between the following methods or properties: 'CSharpExtensions.IsKeyword(SyntaxToken)' and 'VisualBasicExtensions.IsKeyword(SyntaxToken)'	SourceBrowser.Generator	CSWalker.cs	47

The code looks like this:

            if (token.IsKeyword())        // Line with error
            {
                tokenModel = ProcessKeyword(token);
            }
            else if (   token.CSharpKind() == SyntaxKind.IdentifierToken
                     || token.VisualBasicKind() == SyntaxKind.IdentifierToken)
            {
                tokenModel = ProcessIdentifier(token);
            }

Extension resolution doesn't work with aliased using statements. Read more here:
https://stackoverflow.com/questions/3337453/why-do-extension-methods-not-work-with-namespace-aliasing

It looks like the architects of Roslyn decided that logic for each language should reside in separate file.
We could still move most of our logic to a shared file. Thoughts?

**Comment by JoshVarty** [comment]
I'm fairly sure we should be able to achieve it with this. Kirill built ReferenceSource and he says their implementation is language agnostic: https://twitter.com/KirillOsenkov/status/520350789437374464

I can also take a look at this after I wrap up #68 and merge it in. 

It's possible we just can't use those language extensions and need to find a different approach.

**Comment by AmadeusW** [comment]
Hmmm that's interesting and also hard to imagine how they could decouple language information. It's so deeply ingrained in the code! Sure, give it a try.
