### ISSUE TITLE
Upload times seem exceptionally slow.

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#76]
So I was checking that #48 was fixed and I noticed that it took an extremely long time to upload. (~15 minutes).

We should investigate why this was the case and if we can mitigate it. Maybe we can scale our server up a level.

Here's some summary info on the upload. Looks like the CPU usage might be the issue here. We should profile locally and find out bottlenecks. (I suspect it's building the Lucene index)

![image](https://cloud.githubusercontent.com/assets/1249087/5712812/9e4f9c12-9a83-11e4-9e4a-666ea33d8f35.png)

**Comment by AmadeusW** [comment]
wow that took a while!
Since processing is serial, we could log whenever we go to each next step and correlante these timestamps with summary on Azure

**Comment by MarcinJuraszek** [comment]
Did you guys think about using Application Insights for better data visualization on perf and usage?

**Comment by AmadeusW** [comment]
No, I don't know about it. Is [this](https://visualstudiogallery.msdn.microsoft.com/82367b81-3f97-4de1-bbf1-eaf52ddc635a) it?
Btw JSON.net is still processing after 20 minutes, which is at least 20 times slower than my laptop. We definitely need to improve.

**Comment by MarcinJuraszek** [comment]
It's a service on Azure that lets you quite easily get perf and usage telemetry out of your web app.

http://azure.microsoft.com/en-us/services/application-insights/

Btw. is sourceBrowser hosted on Azure?

**Comment by AmadeusW** [comment]
Yes. I'll follow these instructions: do you think that's ok? http://azure.microsoft.com/en-us/documentation/articles/app-insights-monitor-performance-live-website-now/

**Comment by MarcinJuraszek** [comment]
This will give you basic data like request rate, response timing etc. Should be useful to start with.

I was thinking more about custom duration event. They require custom code, but give you more insights into how long custom parts of the codebase took to finish. They are described [here](http://msdn.microsoft.com/en-us/library/dn481100.aspx) under *Log timed events*

**Comment by AmadeusW** [comment]
We'll try to set it up and write code to interface with the insights. Thanks for the link! It looks promising

**Comment by MarcinJuraszek** [comment]
If you set the configs I'm happy to help adding data points into the code later today.

It would also be nice to have some kind of utils class you could just wrap stuff around using an `using` statement and it will log perf for that operation at the end. I'll do some research for libraries like this or write my own if find nothing.

**Comment by AmadeusW** [comment]
The insights are set up. Let me know what do I need to do on the admin side.
Also, can we do generic logging using insights?

**Comment by MarcinJuraszek** [comment]
Yes, you can. You can use events to do so: http://msdn.microsoft.com/en-us/library/dn481100.aspx Adding custom properties to events will let you filter them later in the dashboard by their values.

Question is, how much of logs you want to store and how are you going to use them. I don't know (and can't find any resources) what are the limits of events you can log using Application Insights

**Comment by JoshVarty** [comment]
Newtonsoft.Json is now down to ~1:55. Obviously not ideal to make users wait for that long, but it's a lot more reasonable.
