### ISSUE TITLE
Incorrect routing or controller causes favicon.ico and other assets to return 404

### ISSUE THREAD

**Issue by AmadeusW** [CodeConnect/SourceBrowser#77]
Application Insights pointed out the reason why favicon.ico, robots.txt, Content/search.png and Content/logo.png return 404.
It looks like some route is misconfigured or we're missing a controller for generic files.
![image](https://cloud.githubusercontent.com/assets/1673956/5716063/a9bf7548-9a99-11e4-8e29-562293363919.png)

**Comment by JoshVarty** [comment]
I think this is related to the changes we made when making .cs files browsable...

**Comment by JoshVarty** [comment]
This is not fixed. The files were cached locally and it just seemed like my fix was working.

**Comment by AmadeusW** [comment]
:moneybag:
