### ISSUE TITLE
Clicking through search results does not immediately take user to the target line

### ISSUE THREAD

**Issue by AmadeusW** [CodeConnect/SourceBrowser#79]
Suppose there are two search results:
**1** points to
`http://localhost:57806/Browse/JamesNK/Newtonsoft.Json/Src/Newtonsoft.Json/Serialization/JsonContract.cs#300`, and
**2** points to
`http://localhost:57806/Browse/JamesNK/Newtonsoft.Json/Src/Newtonsoft.Json/Serialization/JsonDictionaryContract.cs#42`

When clicking on the link takes the user to a different HTML page, page does *not* scroll to the specified anchor. User needs to click on the link again (or on another search result which also points to the same HTML page) in order to end up on the target line.

In this example, clicking at results **1, 2, 1, 2** simply loads alternating HTML pages but doesn't take the user to the target line. However, clicking at results **1, 2, 2** takes the user to line 42.

**Comment by JoshVarty** [comment]
Weird. I just noticed this on prod too...

**Comment by JoshVarty** [comment]
It's related to #77. 

This error doesn't let jQuery load everything it needs in order to animate correctly.

![image](https://cloud.githubusercontent.com/assets/1249087/5771006/e1b8d4ce-9d02-11e4-848d-e8ac77eddc1f.png)

**Comment by JoshVarty** [comment]
After fixing #77, this error still persists. 

So I was mistaken earlier. I'll continue investigating.
