### ISSUE TITLE
Get rid of these stupid AssemblyAttributes.cs files

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#89]
I think they appear at the top level because we can't find them on disk. There's likely a bug in the solution analyzer.

![image](https://cloud.githubusercontent.com/assets/1249087/5806270/aaea638c-9fe5-11e4-85c7-bd27927b5be4.png)

**Comment by AmadeusW** [comment]
Good call. They don't bring anything to understanding of the project
