### ISSUE TITLE
Show README at first page.

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#94]
I think it'd be nice if we had the GitHub README displayed on the first page. We have access to it in the Git Repo, we'd just need to figure out how to display Markdown.

**Comment by AmadeusW** [comment]
:+1:

**Comment by AmadeusW** [comment]
I propose that `UploadController.Submit` calls `UploadRepository.ProcessReadme` which turns the markdown file from *GithubStaging* to HTML and puts it in *SB_Files*.
`LookupFolder.cshtml` will be responsible for rendering that HTML (if it exists)

We can use https://www.nuget.org/packages/MarkdownDeep.NET/ which is said to be 15x faster than MarkdownSharp which is 10x faster than Markdown.NET.

Thoughts?
